language: ruby
cache: bundler

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.6
  - 2.7.2
  - 3.0.0
  - jruby-9.2
  - truffleruby
  - ruby-head
  - jruby-head
  - rbx-head
  - mruby-head
  - maglev-head
  - macruby-head
  - ironruby-head
  - opal
  - topaz

gemfile:
  - gemfiles/without_oj.Gemfile
  - gemfiles/with_oj.Gemfile

matrix:
  exclude:
    - rvm: jruby-9.2
      gemfile: gemfiles/with_oj.Gemfile
    - rvm: jruby-head
      gemfile: gemfiles/with_oj.Gemfile
  allow_failures:
    # Single rspec failure, which is strange, leaving it for tracking
    - rvm: truffleruby

script: bundle exec rspec
